#lang hydromel

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import "fifo1-3.mel"

component fifo2(T : type)
    port cp : splice consumer_producer(T)

    instance f = fifo1(T)
    f.c = c

    instance g = fifo1(T)
    g.c = f.p
    p   = g.p
end
